apiVersion: v1
kind: Pod
metadata:
  name: simpleservice
  labels:
    name: simpleservice
spec:
  containers:
  - name: simpleservice-web
    image: mhausenblas/simpleservice:0.5.0
    ports:
    - name: web
      containerPort: 9876
      protocol: TCP
    livenessProbe:
      initialDelaySeconds: 2   # wait this long after restarting to do the first HTTP GET (default 0)
      periodSeconds: 5         # how often to probe (default is 1)
      timeoutSeconds: 1        # how long to wait until timeout occurs (default is 1)
      successThreshold: 1      # min consecutive successes to be considered "up" after a fail (default 1)
      failureThreshold: 3      # how many consecutive fails before pod is restarted (default 3)
      httpGet:                 # send HTTP GET to :9876/health/
        path: /info
        port: 9876
