apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservice
  labels:
    app: webby
spec:
  selector:
    matchLabels:
      app: webby
  replicas: 6
  template:
    metadata:
      labels:
        app: webby
    spec:
      containers:
      - name: webby
        image: bchd.registry/morana-webby
        ports:
        - containerPort: 8888

